Repository aktin/docker-aktin-dwh, pull requests merged in 2025-06, with the labels that each got.

#13 fix: Fix unhealthy wildfly
  src/docker/template.yml
  src/docker/wildfly/Dockerfile
Labels: bug

#14 Closes #8 remove hardcoded credentials
  README.md
  src/docker/template.yml
Labels: enhancement

#15 4 add dev mode to wildfly docker
  .gitignore
  README.md
  src/build.sh
  src/docker/template.yml
  src/docker/wildfly/Dockerfile
  src/resources/versions
  src/resources/wildfly/entrypoint.sh
Labels: enhancement

#29 Task/refactoring compose yml
  README.md
  src/build.sh
  src/docker/database/Dockerfile
  src/docker/httpd/Dockerfile
  src/docker/template.yml
  src/docker/wildfly/Dockerfile
  src/resources/versions
Labels: documentation, enhancement
